# .travis.yml
#
# This is the configuration file to drive Travis CI for Slang.

language: cpp
dist: bionic
# Build and test (clang, gcc) x (debug, release)

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - CONFIGURATION=debug
    - os: linux
      compiler: clang
      env:
        - CONFIGURATION=debug
    - os: linux
      compiler: clang
      env:
        - CONFIGURATION=release
    - os: linux
      compiler: gcc
      env:
        - CONFIGURATION=release

script:
  - export OMP_NUM_THREADS=4
  - export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang/lib'; fi)
  - bash ./get_examplegame.sh && make test